# CI and PR build script
#
# There should be no deep magic here. The developer experience and CI experience
# must remain as close to one another as possible.
#
# Developer experience:

#   npm install
#   (make changes)
#   npm test
#   vsce package
#   (give VSIX to someone for buddy testing)
trigger:
- master

# no `pr` keyword because we want all PRs to run this

pool:
  vmImage: ubuntu-16.04

steps:
# for convenience, we tag CI-produced packages with a version number
# pointing to the commit which was built. for PRs, also include the PR #.
- bash: |
    PACKAGE_VERSION=$(node -p "require('./package.json').version")
    if [ -n "$SYSTEM_PULLREQUEST_PULLREQUESTNUMBER" ]; then
      VERSION_STRING=${PACKAGE_VERSION}-pr-${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER}-$(git rev-parse --short HEAD)
    else
      VERSION_STRING=${PACKAGE_VERSION}-ci-$(git rev-parse --short HEAD)
    fi
    npm --no-git-tag-version version $VERSION_STRING
    echo "##vso[build.updatebuildnumber]${VERSION_STRING}_${BUILD_BUILDID}"
    echo "$PACKAGE_VERSION" > version.txt
  displayName: Set version number of package and build

- task: VisualStudioTestPlatformInstaller@1
  inputs:
    packageFeedSelector: 'nugetOrg'
    versionSelector: 'latestPreRelease'
- task: DeployVisualStudioTestAgent@1
  inputs:
    testMachineGroup: 
    machineUserName: 'test123@test.com'
    machinePassword: 'test123'
    runAsProcess: true